name: secrets
on:
    workflow_dispatch:
jobs:
    secret:
        runs-on: ubuntu-latest
        steps:
            - name: secret exist or not
              run : |
               echo "the secret is set : true"           

            - name: secret accessing
              run: echo "the secret is ${{secrets.MY_SECRET_MESSAGE}}"
              