name: secrets env
on: 
  workflow_dispatch:
jobs:
    secret-env:
        runs-on: ubuntu-latest
        steps:
            - name: using secret mssg as env
              env:
                SECRET_MSSG: ${{secrets.MY_SECRET_MESSAGE}}
              run: |
                echo "the secret is set: true "
                echo "the length of ${#SECRET_MSSG}"
            
            - name: logining in to docker
              env:
                DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                DOCKER_PASS: ${{secrets.DOCKER_TOKEN}}
              run: |
                echo "login successfull"
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin